spring.application.name=application
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
aws.region=${AWS_REGION}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
jwt.secret=${JWT_SECRET: qhaCnOQYkAi3Y4zTjlLxnlgto4kwXvFWl5XGmvyWyAZOikqNDn2dgm7XLxVTeBDa4vr1GhH8aujnp7TnJnwb8A==}
jwt.expiration=86400000
